### ISSUE TITLE
Spam Bug

### ISSUE THREAD

**Issue by FacePalmDodger** [GouveiaXS/angelicxs_free_DrugHarvest#2]
One of my testers found that you can just spam the E button and get the harvested drug as fast as you press, just having to wait 15 seconds from the least time you pressed it to get the last item. You dont even need to still be there. Is there any fix or a way to add a 
delay?

**Comment by GouveiaXS** [comment]
Addressed in V1.3; wait time is dynamic based on each item's gather time.

**Comment by FacePalmDodger** [comment]
It now doesnt allow me to harvest, the 3D markers show up, just dont do anything when pressed. It still works when reverted to 1.2
